python -u run.py \
  --task_id Alitest_DLinear_cpu_72 \
  --data_dir ./data/ \
  --file_name Alibaba2020_ma.csv \
  --model DLinear \
  --seq_len 288 \
  --pred_len 288 \
  --target plan_cpu \
  --e_layers 2 \
  --factor 3 \
  --enc_in 1 \
  --batch_size 64 \
  --gpu 2